name: CI (macOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SDL2
        run: |
          brew update
          brew install sdl2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test --release

      - name: Generate documentation
        run: cargo doc --no-deps

      # Optionally, upload docs as artifact
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: target/doc 